project:
  type: website
  output-dir: docs

website:
  title: "Inflation & S&P500 Analysis"
  navbar: true
  sidebar: 
    style: "floating"

format:
  html:
    theme: cosmos
    css: formatting.css
