<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="James Rix">
<meta name="dcterms.date" content="2026-04-27">

<title>How Do Inflation Metrics Influence S&amp;P500 Returns and Volatility? – Search:</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-6b423f165eeea3787de40cb4f8e821c3.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>

      .quarto-title-block .quarto-title-banner {
        background: #145a9b;
      }
</style>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="formatting.css">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item">
      Search:
      </li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">How Do Inflation Metrics Influence S&amp;P500 Returns and Volatility?</h1>
                      </div>
  </div>
    
  <div class="quarto-title-meta-author">
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-heading">Affiliation</div>
    
      <div class="quarto-title-meta-contents">
      <p class="author">James Rix </p>
    </div>
    <div class="quarto-title-meta-contents">
          <p class="affiliation">
              University of Exeter- Department of Economics
            </p>
        </div>
    </div>

  <div class="quarto-title-meta">

        
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">April 27, 2026</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Search:</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#data" id="toc-data" class="nav-link" data-scroll-target="#data">Data:</a>
  <ul class="collapse">
  <li><a href="#collection" id="toc-collection" class="nav-link" data-scroll-target="#collection">collection</a></li>
  <li><a href="#calculations" id="toc-calculations" class="nav-link" data-scroll-target="#calculations">Calculations</a></li>
  </ul></li>
  <li><a href="#analysis" id="toc-analysis" class="nav-link" data-scroll-target="#analysis">Analysis</a>
  <ul class="collapse">
  <li><a href="#time-series" id="toc-time-series" class="nav-link" data-scroll-target="#time-series">Time series</a></li>
  <li><a href="#scatter-plots" id="toc-scatter-plots" class="nav-link" data-scroll-target="#scatter-plots">Scatter Plots</a></li>
  <li><a href="#regressions" id="toc-regressions" class="nav-link" data-scroll-target="#regressions">Regressions</a></li>
  </ul></li>
  <li><a href="#conclusion-and-findings" id="toc-conclusion-and-findings" class="nav-link" data-scroll-target="#conclusion-and-findings">Conclusion and Findings</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>The stock market plays an essential role in the global economy, aggregating vast amounts of economic data and combining with consumer sentiment to value over 58000 publicly listed companies. The S&amp;P 500 is often considered the best gauge for large cap American stocks, making up around 80% of the US’s market cap. Due to its prevalence it is closely monitored by policy makers to evaluate economic health and is used by institutions and individual investors as a bench mark for performance.</p>
<p>Among macroeconomic indicators such as GDP growth and unemployment rate, inflation plays a significant role in influencing interest rates, firm profitability and investor expectations. Although inflation is known to have a key role in the valuation of equities in the market, the individual elements of inflation and their exact influence on the market remains largely ambiguous.</p>
<p>This report therefore aims to reveal how three inflation metrics correlate to two core performance measures of the S&amp;P500 by answering the following research question:</p>
<p><em>How do Inflation Metrics Correlate with S&amp;P500 Returns and Volatility?</em></p>
<p><strong>Inflation Metrics:</strong></p>
<ul>
<li><strong>Inflation level</strong> (year on year CPI),<br>
</li>
<li><strong>Inflation volatility</strong> (rolling 12 month standard deviation of inflation)<br>
</li>
<li><strong>Inflation surprise</strong> (Difference between inflation and inflation expectations)</li>
</ul>
<p><strong>S&amp;P500 Measures:</strong></p>
<ul>
<li><strong>S&amp;P500 monthly returns</strong></li>
<li><strong>S&amp;P500 volatility</strong> (rolling 12-month standard deviation of returns).</li>
</ul>
</section>
<section id="data" class="level2">
<h2 class="anchored" data-anchor-id="data">Data:</h2>
<section id="collection" class="level3">
<h3 class="anchored" data-anchor-id="collection">collection</h3>
<p>Inflation data is easily obtainable from the FRED using the “fredapi” library in python and a private API key collected by creating an account with the FRED. This report utilises two datasets from the FRED: 1) CPIAUCSL, which contains monthly data on cpi for all urban consumers in the USA (seasonally adjusted) and 2) MICH, which contains monthly data on University of Michigan consumer inflation expectations.</p>
<p>S&amp;P500 data can be retrieved from yahoo finance using the yfinance python library using the S&amp;P500 ticker “^GSPC”. Unlike the FRED S&amp;P500 data is recorded daily excluding weekends and bank holidays, thus data had to be resampled to monthly by extracting the first record from each month. Redundant columns were removed so the data frame contained only the date and the corresponding S&amp;P500 closing value. Missing values were filled using the pandas function “interpolate()”.</p>
<p>In this report a 25 year window will be used, taking data from 2001/01/01 - 2025/12/31, resulting in 300 records.</p>
</section>
<section id="calculations" class="level3">
<h3 class="anchored" data-anchor-id="calculations">Calculations</h3>
<p>The following variables were constructed for the analysis:</p>
<p><strong>S&amp;P500 monthly returns(%):</strong> <span class="math display">\[
\color{gray}{
R_t = \frac{S\&amp;P500_t - S\&amp;P500_{t-1}}{S\&amp;P500_{t-1}} \times 100
}
\]</span></p>
<p><strong>S&amp;P500 volatility(%):</strong> <span class="math display">\[
\color{gray}{
\sigma_t = \sqrt{\frac{1}{n-1} \sum_{i=0}^{n-1} (R_{t-i} - \bar{R}_t)^2}, \quad n = 12
}
\]</span></p>
<ul>
<li>Note: This can be calculated using the pandas function: <code>R.rolling(12).std()</code></li>
</ul>
<p><strong>Year-on-year inflation(%):</strong> <span class="math display">\[
\color{gray}{
\pi_t = \frac{CPI_t - CPI_{t-1}}{CPI_{t-1}} \times 100
}
\]</span></p>
<p><strong>Inflation volatility(%):</strong> <span class="math display">\[
\color{gray}{
\sigma_t = \sqrt{\frac{1}{n-1} \sum_{i=0}^{n-1} (\pi_{t-i} - \bar{\pi}_t)^2}, \quad n = 12
}
\]</span></p>
<ul>
<li>Note: This can be calculated using the pandas function: <code>π.rolling(12).std()</code></li>
</ul>
<p><strong>Inflation surprise(PP):</strong> <span class="math display">\[
\color{gray}{
S_t = \pi - \pi^E
}
\]</span></p>
<ul>
<li>Where <span class="math inline">\(\pi^E\)</span> = Inflation Expectations</li>
</ul>
</section>
</section>
<section id="analysis" class="level2">
<h2 class="anchored" data-anchor-id="analysis">Analysis</h2>
<section id="time-series" class="level3">
<h3 class="anchored" data-anchor-id="time-series">Time series</h3>
<p>To set the scene for my analysis, <em>Figure 1A</em> displays a combined time series for all 5 of my variables of interest sampled monthly, with <em>Figure 1B</em> abstracting further to a yearly sample frequency. From first glance the figures portray some noticeable features: Large market volatility from mid 2008 - mid 2010 (the Global Financial Crisis) and 2020-2021 (Covid 19), there appears to be some positive correlation between S&amp;P500 volatility and inflation volatility and inflation and inflation surprise seem to be positively correlated.</p>
<div class="quarto-layout-panel" data-layout-nrow="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 100.0%;justify-content: flex-start;">
<p><img src="Outputs/Figures/combined_timeseries_monthly.png" class="img-fluid" alt="Combined Time Series"> <img src="Outputs/Figures/combined_timeseries_yearly.png" class="img-fluid" alt="Combined Time Series"></p>
</div>
</div>
</div>
<p><strong>Figure 1.</strong> <em>Time‑series plots of inflation metrics against S&amp;P500 returns and volatility. Figure A (top) Monthly data frequency. Figure B (bottom) yearly data frequency.</em></p>
<p>While the time series plots provide an initial overview of how inflation metrics and the s&amp;P500 move over time, time series graphs are mostly useful for visualising the influence of major events such as the global financial crisis and Covid 19 and portraying long run trends. The value the time series provide in comparing relationships between variables is diminutive.</p>
</section>
<section id="scatter-plots" class="level3">
<h3 class="anchored" data-anchor-id="scatter-plots">Scatter Plots</h3>
<p>To begin investigating relationship between inflation metrics and S&amp;P500 returns and volatility, scatter plots can be used to provide a visual representation and an intuitive preview of what later regressions may uncover. To aid in the visual interpretation a line of best fit has been plotted on each graph. A tightly bound trend around the line of best fit hints at a strong positive or negative relationship, conversely a cloud of points with no clearly visible pattern may point at a weak or absent correlation.</p>
<p>On visual inspection of <em>Figure 2</em> there seems to be extremely little correlation between each of the inflation metrics plotted against S&amp;P500 returns. Calculated r squared values are extremely small hinting that the relationship between inflation metrics and S&amp;P500 returns is extremely week and running a simple linear regression yields extremely high P values, meaning any observable correlation is statistically insignificant.</p>
<div class="quarto-layout-panel" data-layout-ncol="3">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 33.3%;justify-content: center;">
<p><img src="Outputs/Figures/sp500_r_inflation.png" class="img-fluid" alt="S&amp;P500 Returns Against Inflation"></p>
</div>
<div class="quarto-layout-cell" style="flex-basis: 33.3%;justify-content: center;">
<p><img src="Outputs/Figures/sp500_r_inflation_v.png" class="img-fluid" alt="S&amp;P500 Returns Against Inflation Volatility"></p>
</div>
<div class="quarto-layout-cell" style="flex-basis: 33.3%;justify-content: center;">
<p><img src="Outputs/Figures/sp500_r_inflation_s.png" class="img-fluid" alt="S&amp;P500 Returns Against Inflation Surprise"></p>
</div>
</div>
</div>
<p><strong>Figure 2.</strong> <em>Inflation metrics: Inflation - Figure A (left), inflation Volatility - Figure B (middle) and inflation surprise - Figure C (right), against S&amp;P500 returns.</em></p>
<p>Looking into <em>Figure 3</em>, there is visual evidents of correlation between inflation metrics and inflation volatility albeit still relatively weak. On calculation P values are revealed to be extremely small hinting at a statistically significant relationship, however, r squared values also remain relatively small with the highest of them being 0.21 for inflation volatility against S&amp;P500 volatility – meaning 21% of the variation in S&amp;P500 volatility can be explained by inflation volatility.</p>
<div class="quarto-layout-panel" data-layout-ncol="3">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 33.3%;justify-content: center;">
<p><img src="Outputs/Figures/sp500_v_inflation.png" class="img-fluid" alt="S&amp;P500 Volatility Against Inflation"></p>
</div>
<div class="quarto-layout-cell" style="flex-basis: 33.3%;justify-content: center;">
<p><img src="Outputs/Figures/sp500_v_inflation_v.png" class="img-fluid" alt="S&amp;P500 Volatility Against Inflation Volatility"></p>
</div>
<div class="quarto-layout-cell" style="flex-basis: 33.3%;justify-content: center;">
<p><img src="Outputs/Figures/sp500_v_inflation_s.png" class="img-fluid" alt="S&amp;P500 Volatility Against Inflation Surprise"></p>
</div>
</div>
</div>
<p><strong>Figure 3.</strong> <em>Inflation metrics: Inflation - Figure A (left), inflation Volatility - Figure B (middle) and inflation surprise - Figure C (right), against S&amp;P500 volatility.</em></p>
<p>After inspecting <em>Figure 2</em> and <em>Figure 3</em>, there appears to be heteroskedasticity, thus robust standard errors should be used later on in my regressions. Additionally, there is visible clustering around the inflation level of 2-3%, inflation volatility from 0-1PP and inflation surprise of -2-1PP. Economically these patterns make sense, given the FED’s inflation target of 2% and inflation surprise being predominantly negative due to a multitude of economic factors. Furthermore, the plots of inflation vs S&amp;P500 volatility and inflation surprise vs S&amp;P500 volatility appear to follow a nonlinear relationship, this this should also be tested.</p>
</section>
<section id="regressions" class="level3">
<h3 class="anchored" data-anchor-id="regressions">Regressions</h3>
<p>Having visualised the relationships between inflation metrics and S&amp;P500 returns and volatility, I now extend my analysis by modelling more complex regressions. Note throughout this analysis robust standard errors (HC1) are used in regressions to combat heterogeneity and coefficients are standardised to allow meaningful comparison between regressors.</p>
<p>To start , S&amp;P500 returns were regressed on the three inflation metrics:</p>
<p><span class="math display">\[
R_t = \alpha + \beta_1 \pi_t + \beta_2 \sigma_t^{\pi} + \beta_3 S_t + u_t
\]</span></p>
<p>Our earlier assumption based off of figure 2 was confirmed, none of the inflation metrics had statistically significant relationship with S&amp;P500 returns, with the model explaining almost none of S&amp;P500 returns (Adj. R-squared -0.003).</p>
<p>However, markets do not always react instantly to new information and price adjustments may be delayed. To test whether inflation metrics have predictive power on S&amp;P500 returns I then regressed the same model but with the inflation metrics lagged by 1 month:</p>
<p><span class="math display">\[
R_t = \alpha + \beta_1 \pi_{t-1} + \beta_2 \sigma^{\pi}_{t-1} + \beta_3 S_{t-1} + u_t
\]</span></p>
<p>The results remain largely unchanged, with all metrics remaining statistically insignificant and adj. R-squared only increasing to 0.011, revealing past inflation conditions do not predict future S&amp;P500 returns.</p>
<p>We now turn to investigate the relationship between the inflation metrics and S&amp;P500 volatility. As noted earlier, visual inspection of <em>Figure 3A</em> and <em>Figure 3B</em> suggest a non-linear relationships of inflation and inflation surprise with S&amp;P500 volatility. To account for this squared terms for each of these respective metrics have been included in the model:</p>
<p><span class="math display">\[
\sigma^{SP500}_t = \alpha + \beta_1 \pi_t + \beta_2 \sigma^{\pi}_t + \beta_3 S_t + \beta_4 \pi_t^2 + \beta_5 S_t^2 + u_t
\]</span></p>
<p>As seen in <em>Figure 4</em>, this model explains 36.2% of the variation in monthly S&amp;P500 volatility, a significantly stronger result than the models relating inflation metrics to S&amp;P500 returns. All variables were statistically significant except the squared inflation surprise term. The model suggests that inflation volatility and inflation surprise both have a statistically significant positive correlation with S&amp;P500 volatility, where a 1 standard deviation (SD) increase in either metric is associated with a 0.79 SD increase in S&amp;P500 volatility. Conversely inflation has a statistically significant negative relationship with S&amp;P500 volatility, where a 1 SD increase in inflation is associated with a 1.50 SD decrease in S&amp;P500 volatility.</p>
<div id="f28d3eb9" class="cell" data-execution_count="1">
<div class="cell-output cell-output-stdout">
<pre><code>                  Results: Ordinary least squares
====================================================================
Model:                OLS              Adj. R-squared:     0.362    
Dependent Variable:   SP500_volatility AIC:                1165.9034
Date:                 2026-04-27 23:17 BIC:                1188.1261
No. Observations:     300              Log-Likelihood:     -576.95  
Df Model:             5                F-statistic:        43.56    
Df Residuals:         294              Prob (F-statistic): 1.56e-33 
R-squared:            0.373            Scale:              2.7973   
--------------------------------------------------------------------
                      Coef.  Std.Err.    z    P&gt;|z|   [0.025  0.975]
--------------------------------------------------------------------
const                 4.3058   0.0966 44.5901 0.0000  4.1165  4.4950
YOY_inflation        -1.4905   0.3599 -4.1419 0.0000 -2.1958 -0.7852
Inflation_volatility  0.7870   0.0983  8.0076 0.0000  0.5944  0.9796
Inflation_surprise    0.7924   0.2202  3.5983 0.0003  0.3608  1.2241
Inflation_sqrd        0.2463   0.4497  0.5477 0.5839 -0.6350  1.1276
Surprise_sqrd         0.5930   0.1744  3.4002 0.0007  0.2512  0.9348
--------------------------------------------------------------------
Omnibus:               18.669        Durbin-Watson:           0.133 
Prob(Omnibus):         0.000         Jarque-Bera (JB):        21.461
Skew:                  0.546         Prob(JB):                0.000 
Kurtosis:              3.725         Condition No.:           13    
====================================================================
Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)</code></pre>
</div>
</div>
<p><strong>Figure 4.</strong> <em>Regression results from regressing S&amp;P500 volatility on inflation metrics.</em></p>
<p>Following the previous approach, I will now regress S&amp;P500 volatility on the inflation metrics lagged by 1 month, to understand the metrics’ predictive effect on market volatility, as specified in the following model:</p>
<p><span class="math display">\[
\sigma^{SP500}_t = \alpha + \beta_1 \pi_{t-1} + \beta_2 \sigma^{\pi}_{t-1} + \beta_3 S_{t-1} + u_t
\]</span></p>
<p>Replacing lagged inflation variables in the model yeilds substantially different results, as shown in <em>Figure 5</em>. Inflation surprise is no longer statistically significant, the magnitude of the effect of inflation is reduced to -0.79 SD and the effect of inflation volatility increases to 1.00 SD.</p>
<div id="ca595609" class="cell" data-execution_count="2">
<div class="cell-output cell-output-stdout">
<pre><code>                  Results: Ordinary least squares
====================================================================
Model:                OLS              Adj. R-squared:     0.938    
Dependent Variable:   SP500_volatility AIC:                467.7166 
Date:                 2026-04-27 23:17 BIC:                486.2355 
No. Observations:     300              Log-Likelihood:     -228.86  
Df Model:             4                F-statistic:        911.2    
Df Residuals:         295              Prob (F-statistic): 1.28e-164
R-squared:            0.938            Scale:              0.27380  
--------------------------------------------------------------------
                      Coef.  Std.Err.    z     P&gt;|z|   [0.025 0.975]
--------------------------------------------------------------------
const                 4.3058   0.0302 142.5255 0.0000  4.2466 4.3650
SP500_volatility_lag  1.9700   0.0451  43.6635 0.0000  1.8815 2.0584
YOY_inflation        -0.0496   0.0633  -0.7845 0.4327 -0.1737 0.0744
Inflation_volatility  0.0710   0.0467   1.5203 0.1284 -0.0205 0.1626
Inflation_surprise   -0.0420   0.0508  -0.8269 0.4083 -0.1415 0.0575
--------------------------------------------------------------------
Omnibus:               68.204       Durbin-Watson:          1.242   
Prob(Omnibus):         0.000        Jarque-Bera (JB):       1390.633
Skew:                  -0.167       Prob(JB):               0.000   
Kurtosis:              13.542       Condition No.:          4       
====================================================================
Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)</code></pre>
</div>
</div>
<p><strong>Figure 5.</strong> <em>Regression results from regressing S&amp;P500 volatility on lagged inflation metrics.</em></p>
<p>Economically the results for inflation volatility and inflation surprise make sense. Having high inflation volatility indicates high uncertainty regarding inflation. During these times, households and firms struggle to predict monetary policy response and real interest rates, leading to fluctuations in investment habits and asset pricing and therefore increased market volatility. Similarly, for inflation surprise, when households or firms wrongly predict inflation, they re-evaluate their expectations for future monetary policy and asset pricing, leading to fluctuations in the stock market, although unlike inflation volatility this effect is short-lived and does not contribute to market volatility in the following month. Additionally the positive and statistically significant squared term for inflation surprise indicates a nonlinear relationship, where large inflation surprises disproportionately increase volatility in the market.</p>
<p>The negative coefficient for inflation suggests that in times of high inflation, where inflation volatility and inflation surprise are accounted for there is a negative relationship between stable and predictable inflation and S&amp;P500 volatility. Additionally the VIF value between inflation and inflation surprise is 4.8 indicating moderate collinearity, thus making coefficient estimates less reliable.</p>
<p>To address multicollinearity between inflation and inflation surprise the following model will be run:</p>
<p><span class="math display">\[
\sigma^{SP500}_t = \alpha + \beta_1 \pi^{std}_t + \beta_2 (\sigma^{\pi}_t)^{std} + u_t
\]</span></p>
<p>After discarding inflation surprise from the model, the coefficient for inflation has been substantially reduced (from −1.49 to −0.6). This suggests the originally observed strong negative relationship was most likely overstated due to shared variation between inflation and inflation surprise.</p>
<p>To explore further how inflation and inflation volatility jointly influence S&amp;P500 volatility the following model will be run:</p>
<p><span class="math display">\[
\sigma^{SP500}_t = \alpha + \beta_1 \pi^{std}_t + \beta_2 (\sigma^{\pi}_t)^{std} + \beta_3\left( \pi^{std}_t \cdot (\sigma^{\pi}_t)^{std} \right)+ u_t
\]</span></p>
<p>Similar to the previous models, as seen in figure 6 this model shows a strong and statistically significant positive relationship between inflation volatility and S&amp;P500 volatility. The interaction term between inflation and inflation volatility is negative and also statistically significant. However, importantly inflation is now statistically insignificant with a p-value of 0.58.</p>
<div id="e93b7152" class="cell" data-execution_count="3">
<div class="cell-output cell-output-stdout">
<pre><code>                   Results: Ordinary least squares
======================================================================
Model:                OLS               Adj. R-squared:      0.330    
Dependent Variable:   SP500_volatility  AIC:                 1178.6915
Date:                 2026-04-27 23:17  BIC:                 1193.5067
No. Observations:     300               Log-Likelihood:      -585.35  
Df Model:             3                 F-statistic:         84.91    
Df Residuals:         296               Prob (F-statistic):  1.16e-39 
R-squared:            0.337             Scale:               2.9384   
----------------------------------------------------------------------
                        Coef.  Std.Err.    z    P&gt;|z|   [0.025  0.975]
----------------------------------------------------------------------
const                   4.3058   0.0990 43.5070 0.0000  4.1118  4.4997
YOY_inflation           0.1390   0.2510  0.5536 0.5798 -0.3530  0.6309
Inflation_volatility    1.3797   0.0999 13.8043 0.0000  1.1838  1.5756
Inflation_x_volatility -0.9708   0.2196 -4.4201 0.0000 -1.4013 -0.5403
----------------------------------------------------------------------
Omnibus:               27.767         Durbin-Watson:            0.115 
Prob(Omnibus):         0.000          Jarque-Bera (JB):         33.624
Skew:                  0.720          Prob(JB):                 0.000 
Kurtosis:              3.786          Condition No.:            5     
======================================================================
Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)</code></pre>
</div>
</div>
<p><strong>Figure 6.</strong> <em>Regression results from regressing S&amp;P500 volatility inflation and inflation volatility with an interaction term.</em></p>
<p>The negative interactive term suggests the effect of inflation volatility on market volatility decreases as inflation increases. This suggests that the previous negative correlation of inflation with S&amp;P500 volatility was not a genuine relationship and instead the coefficient captured the role inflation plays in reducing the effect of volatility at levels of high inflation. Economically this makes sense, in times of low inflation, sudden fluctuations are more likely to come as a greater surprise compared to fluctuations in times of high inflation and so can cause greater instability in the market.</p>
<p>For my final regression model I incorporate the concept of volatility persistence – the idea that market volatility is highly correlated with volatility from previous periods. To examine how inflation, inflation volatility and inflation surprise compare in significance and magniture to this effect I will use the model:</p>
<p><span class="math display">\[
\sigma^{SP500}_t = \alpha + \beta_1 (\sigma^{SP500}_{t-1})^{std} + \beta_2 \pi^{std}_t + \beta_3 (\sigma^{\pi}_t)^{std} + \beta_4 S^{std}_t + u_t
\]</span></p>
<p>The inclusion of past S&amp;P500 volatility in my model produces an interesting result. As seen in figure 7, the model yields a very high R-squared (0.938), yet the relationship of inflation, inflation volatility and inflation surprise to S&amp;P500 volatility all become statistically insignificant (p-values: 0.433, 0.128, 0.408 respectively).</p>
<p>This strongly supports the economic phenomena of volatility persistence and volatility clustering. It suggests that past volatility is the strongest predictor of future volatility and once accounted for, the inflation metrics provide almost no explanatory power. This suggests that the significant results for inflation metrics discovered in previous models, were likely due to omitting volatility persistence rather than reflecting a meaningful relationship.</p>
<div id="6e267b4e" class="cell" data-execution_count="4">
<div class="cell-output cell-output-stdout">
<pre><code>                  Results: Ordinary least squares
====================================================================
Model:                OLS              Adj. R-squared:     0.938    
Dependent Variable:   SP500_volatility AIC:                467.7166 
Date:                 2026-04-27 23:17 BIC:                486.2355 
No. Observations:     300              Log-Likelihood:     -228.86  
Df Model:             4                F-statistic:        911.2    
Df Residuals:         295              Prob (F-statistic): 1.28e-164
R-squared:            0.938            Scale:              0.27380  
--------------------------------------------------------------------
                      Coef.  Std.Err.    z     P&gt;|z|   [0.025 0.975]
--------------------------------------------------------------------
const                 4.3058   0.0302 142.5255 0.0000  4.2466 4.3650
SP500_volatility_lag  1.9700   0.0451  43.6635 0.0000  1.8815 2.0584
YOY_inflation        -0.0496   0.0633  -0.7845 0.4327 -0.1737 0.0744
Inflation_volatility  0.0710   0.0467   1.5203 0.1284 -0.0205 0.1626
Inflation_surprise   -0.0420   0.0508  -0.8269 0.4083 -0.1415 0.0575
--------------------------------------------------------------------
Omnibus:               68.204       Durbin-Watson:          1.242   
Prob(Omnibus):         0.000        Jarque-Bera (JB):       1390.633
Skew:                  -0.167       Prob(JB):               0.000   
Kurtosis:              13.542       Condition No.:          4       
====================================================================
Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)</code></pre>
</div>
</div>
<p><strong>Figure 7.</strong> <em>Regression results from regressing S&amp;P500 volatility on previous period S&amp;P500 volatility and inflation metrics.</em></p>
</section>
</section>
<section id="conclusion-and-findings" class="level2">
<h2 class="anchored" data-anchor-id="conclusion-and-findings">Conclusion and Findings</h2>
<p>The intention for this report was to investigate the relationship between 3 inflation metrics: year-on-year inflation, inflation volatility and inflation surprise, and how they influence two metrics of stock market behaviour: S&amp;P500 monthly returns and S&amp;P500 volatility. The analysis utilised 300 monthly data points over a 25 year time frame and has produced a set of results that broadly align with current economic understanding.</p>
<p>The first part of the analysis focused on the relationship between S&amp;P500 returns and inflation metrics in contemporaneous and lagged regression models. Surprisingly the results were statistically insignificant, suggesting that the inflation dynamics mentioned do not have any meaningful impact on current stock market returns, nor do they have any predictive power for future returns.</p>
<p>In contrast, the relationship between the inflation metrics and S&amp;P500 volatility is considerably stronger. Initial inspection of the scatter plots suggested positive correlations between S&amp;P500 volatility and inflation volatility and inflation surprise and negative correlations S&amp;P500 volatility and inflation. Subsequent regressions confirm these statistically significant relationships. Additionally, inflation surprise has a nonlinear effect on S&amp;P500 volatility, where large surprises disproportionately increase volatility. These results are consistent with economic intuition as uncertainty in inflation, either caused by volatility or surprises, increases uncertainty in the market due to difficulties predicting monetary policy and real interest rates.</p>
<p>However, after further investigation, the relationship between inflation and S&amp;P500 volatility appears to be unreliable. When including an interaction term in the model between inflation and inflation volatility, inflation became statistically insignificant, while the interaction term remains statistically significant. This suggests that inflation does not independently influence S&amp;P500 volatility, but instead dampens the impact of inflation volatility on S&amp;P500 volatility at high levels of inflation. This result aligns with investment behaviour and monetary policy dynamics. At low inflation levels volatility often comes as a greater shock resulting in larger market corrections and greater volatility. Additionally at already high levels of inflation investors have clearer expectations of how monetary policy will be used, reducing the possibility of monetary policy surprises.</p>
<p>The final model incorporates the well documented phenomena of volatility persistence in financial markets. The model yielded a substantially larger adjusted R-squared, while inflation, inflation volatility and inflation surprise were all deemed insignificant. These results show that past S&amp;P500 volatility is the predominant driver for future S&amp;P500 volatility and the relationships previously identified were likely due to omitted variable bias caused by neglecting volatility persistence.</p>
<p>Overall, the results suggest although in simpler models inflation volatility and inflation surprise appear to have a positive influence on S&amp;P500 volatility, surprisingly after accounting for S&amp;P500 volatility in the previous period, they provide no significant insight into market volatility.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>